name: kotoba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  japanese_word_tokenizer: ^0.0.3
  kanji_dictionary: ^1.0.5+1
  unofficial_jisho_api: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
