name: Build kotoba

on:
  push:
    branches:
      main

jobs:
  build:
    name: Release for android
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build apk
    - name: Release artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Kotoba Worjflow Build Artifact"
        path: "build/app/outputs/flutter-apk/app-release.apk"
      
